language: generic

before_install:
  - docker build -t rmduran65/mul-doc -f ./client/dockerfile.dev ./client
  
script:
  - docker run -e CI=true rmduran65/mul-doc npm run test
  
after_success:
  - docker build -t rmduran65/multi-client ./client
  - docker build -t rmduran65/multi-nginx ./nginx
  - docker build -t rmduran65/multi-server ./server
  - docker build -t rmduran65/multi-worker ./worker
  # Log in the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rmduran65/multi-client
  - docker push rmduran65/multi-nginx
  - docker push rmduran65/multi-server
  - docker push rmduran65/multi-worker
  